### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cloud')

### ISSUE THREAD

**Issue by Erchoc** [nestjs/elasticsearch#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

such as #794 ，when i start the nest application，the error show

the @794 issue opened on Apr 7, 2022，marked `bug`

so when will resolve this problem?

### Minimum reproduction code

https://github.com/febouge/elastic-nest-issue

### Steps to reproduce

npm i
npm run start

### Expected behavior

the server should running.

### Package version

9.1.4

### NestJS version

9.1.4

### Node.js version

16.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

such all.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
