### ISSUE TITLE
ConnectionError: other side closed

### ISSUE THREAD

**Issue by OttlikG** [nestjs/elasticsearch#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My elasticsearch listening on 9200 port. I configured the serve side @nestjs/elasticsearch with auth credentials and tls certificate. This is the configuration I have:
```js
imports: [
    ElasticsearchModule.register({
      node: 'http://localhost:9200',
      auth: {
        username: 'elastic',
        password: 'xxx',
      },
      tls: {
        ca: fs.readFileSync('../http_ca.crt'),
        rejectUnauthorized: false,
      },
    }),
  ],
```
When I try to run a simple search it gives me the following error:
```
ConnectionError: other side closed - Local: 127.0.0.1:53971, Remote: 127.0.0.1:9200
    at SniffingTransport.request (/Users/gaborottlik/Developer/My/adstore-api/node_modules/@elastic/transport/src/Transport.ts:585:17)
    at ElasticsearchService.SearchApi [as search] (/Users/gaborottlik/Developer/My/adstore-api/node_modules/@elastic/elasticsearch/src/api/api/search.ts:85:10)
    at AppService.getHello (/Users/gaborottlik/Developer/My/adstore-api/src/app.service.ts:28:20)
    at AppController.getHello (/Users/gaborottlik/Developer/My/adstore-api/src/app.controller.ts:10:12)
    at /Users/gaborottlik/Developer/My/adstore-api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/gaborottlik/Developer/My/adstore-api/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

What's interesting that when I run search with the exact same config in an isolated environment without the `@nestjs/elasticsearch` library I get back result.

### Minimum reproduction code

https://gist.github.com/OttlikG/3f68fcc8ef5357200ffdbaf5f6d46a95

### Steps to reproduce

Generate a nest project.
Change the file from the gist accordingly.
[Start a single node cluser with docker](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)

### Expected behavior

I expect to get the same stored result as I get from `https://localhost:9200/ad-book/_search`

### Package version

9.0.0

### NestJS version

9.3.3

### Node.js version

16.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
