### ISSUE TITLE
Analytics results Elastic GUI

### ISSUE THREAD

**Issue by DmitriyIudokhin** [nestjs/elasticsearch#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i am sending query with 'search' method i dont have any query statistics in Elasticsearch appSearch. 
But when i send it with axios directly to engine,  Elastic records my query string and show analytics in their GUI.

### Minimum reproduction code

https://gist.github.com/DmitriyIudokhin/7bff9837d05d7944f5c837923157b384

### Steps to reproduce

Search function returns correct result but not records in Elastic GUI. 
Elastic GUI can record query string only when request to engine:

 ```
const url = ELASTIC_SEARCH_URL + ELASTIC_SEARCH_ENGINE + '/search';
        const headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer search_xxxxxxxxxxxxxxx',
        };

        let aElasticQuery: iElasticQuery = {
            query: pBody.query,
            filters: pBody.filters,
            sort: pBody.sort,
            page: pBody.page
        }

        let aConfig = {
            method: 'post',
            maxBodyLength: Infinity,
            url: url,
            headers: headers,
            data: JSON.stringify(aElasticQuery)
        };

  
          let aResult = await axios.request(aConfig)
```

### Expected behavior

Receive all query results **but with  recording in analytics Elasticsearch GUI**

### Package version

9.0.0

### NestJS version

7.6.15

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
