### ISSUE TITLE
Return value from search subscribe

### ISSUE THREAD

**Issue by kjetilhp** [nestjs/elasticsearch#4]
I'm trying to do a simple search and process the result inside subscribe, but it seems that the return values and the typing does not match

```
.search(...).subscribe(res => {
  // according to typing I should get a SearchResponse having hits, took etc.
  // but get an array where the first element is the searchresponse and the 
  // second is the http return code
})
```

see picture
![image](https://user-images.githubusercontent.com/393416/52114873-7fad3980-260d-11e9-98ca-0d1ea091e008.png)

**Comment by kamilmysliwiec** [comment]
It looks like an issue with the underlying `@types/elasticsearch`(?)

**Comment by piotr-zurek** [comment]
I facing the same issue. ES logs shows that response from ES API is just an object but .search() return array with 1 element.
