### ISSUE TITLE
Error in connection to es

### ISSUE THREAD

**Issue by Antart1ca** [nestjs/elasticsearch#573]
**Error message**
(node:13431) UnhandledPromiseRejectionWarning: ProductNotSupportedError: The client noticed that the server is not a supported distribution of Elasticsearch

**Code:**
```
ElasticsearchModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        node: configService.get('ELASTICSEARCH_NODE'),
        auth: {
          username: configService.get('ELASTICSEARCH_USERNAME'),
          password: configService.get('ELASTICSEARCH_PASSWORD'),
        },
      }),
      inject: [ConfigService],
    }),
```

**Please NOTE:**
But it works version 7.1.0 and doen't work 8.0.0

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
