### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by mailtosubbu7** [nestjs/elasticsearch#71]
I am sorry to posting this here..

Is there any sample project how to insert/read data from elasticsearch using nestjs/elaticsearch package?
I am not able to find an correct example.. Please help me.

Thanks,
Subu

**Comment by kamilmysliwiec** [comment]
You can follow any existing `elasticsearch` tutorial for Node.js. `@nestjs/elasticsearch` is just a wrapper around the official package
