### ISSUE TITLE
Support opensearch client fork

### ISSUE THREAD

**Issue by smiley-uriux** [nestjs/elasticsearch#711]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The team maintaining the official elasticsearch-js client decided to drop support for OSS distributions as part of a minor version bump, breaking many people's applications that may have been using an OSS version like that of AWS's managed elasticsearch service. (see https://github.com/elastic/elasticsearch-js/issues/1519) 

### Describe the solution you'd like

While it's certainly possible to pin down the official client to a previous version, it would be great if this little library could also support the opensearch client (https://github.com/opensearch-project/opensearch-js), since as of now they appear to be drop in replacements. 

### What is the motivation / use case for changing the behavior?

I think many in the community will be transitioning away from the official client, if only to avoid getting caught in future political battles. Forking this library is certainly possible and is likely what I'll do if there is no interest here in supporting both clients.

**Comment by kamilmysliwiec** [comment]
This (`@nestjs/elasticsearch`) is a very tiny library that is supposed to make the integration _slightly_ easier. If you need to integrate a different client, you can follow the source code of this package. Currently, we don't plan to maintain 2 different clients (as we have no bandwidth to do so) but it may change in the future.
