### ISSUE TITLE
Build fails on non UNIX systems

### ISSUE THREAD

**Issue by jbw** [nestjs/elasticsearch#728]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

PR #727

### Describe the regression

Package fails to build on Windows. 

### Minimum reproduction code

```ts
npm run build
```

### Expected behavior

Package builds on Windows.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/elasticsearch/pull/727
