### ISSUE TITLE
Unable to init Elasticsearch Service

### ISSUE THREAD

**Issue by febouge** [nestjs/elasticsearch#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, 

I'm trying to use the module to connect to a self-managed Elasticsearch instance (see minimal example attached). But whenever I try to use ElasticsearchService, it seems that the ClientOptions are not being passed to the Client instance. I get the error: 

```
ERROR [ExceptionHandler] Cannot read property 'cloud' of undefined 
```
thrown in 
```
node_modules/@elastic/elasticsearch/src/client.ts:127:15
```
If you see the [client code](https://github.com/elastic/elasticsearch-js/blob/main/src/client.ts#L127), the only option is that 'opts' are undefined.

I have also tried using ElasticsearchModule.register (with a static object) to discard any async configuration issue and it also failed.
The same configuration used directly on elastic Client is working fine.

So maybe the module is not providing the ClientOptions properly?

### Minimum reproduction code

https://github.com/febouge/elastic-nest-issue

### Steps to reproduce

1. yarn install
2. yarn start:dev

### Expected behavior

The ElasticsearchService should init properly with the module options.

### Package version

8.1.0

### NestJS version

8.4.4

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
